import { StyleSheet } from "react-native";

export const questionnaireStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F7FA",
  },
  progressHeader: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E8ECF1",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  progressHeaderText: {
    fontSize: 14,
    color: "#6C63FF",
    marginBottom: 8,
    fontWeight: "600",
    letterSpacing: 0.5,
  },
  progressBar: {
    height: 6,
    backgroundColor: "#E8ECF1",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#6C63FF",
    borderRadius: 3,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  singleQuestionContainer: {
    padding: 24,
    backgroundColor: "#FFFFFF",
    margin: 16,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  questionNumber: {
    fontSize: 14,
    color: "#8E8E93",
    fontWeight: "500",
  },
  required: {
    fontSize: 14,
    color: "#FF3B30",
    fontWeight: "600",
  },
  questionText: {
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 24,
    color: "#1C1C1E",
    lineHeight: 30,
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1C1C1E",
    marginBottom: 20,
    letterSpacing: -0.5,
  },
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 15,
    color: "#3A3A3C",
    marginBottom: 8,
    fontWeight: "500",
  },
  input: {
    borderWidth: 1.5,
    borderColor: "#E8ECF1",
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    backgroundColor: "#F8F9FB",
    color: "#1C1C1E",
  },
  inputFocused: {
    borderColor: "#6C63FF",
    backgroundColor: "#F5F3FF",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 20,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#E8ECF1",
  },
  button: {
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 12,
    minWidth: 120,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  prevButton: {
    backgroundColor: "#F1F1F6",
  },
  nextButton: {
    backgroundColor: "#6C63FF",
  },
  submitButton: {
    backgroundColor: "#34C759",
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  prevButtonText: {
    color: "#3A3A3C",
  },
  disabledText: {
    color: "#B8B8BE",
  },
  paceContainer: {
    marginTop: 12,
    padding: 16,
    backgroundColor: "#F5F3FF",
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#6C63FF",
  },
  paceContainerEmpty: {
    marginTop: 12,
    padding: 16,
    backgroundColor: "#F8F9FB",
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#E8ECF1",
  },
  paceLabel: {
    fontSize: 14,
    color: "#6C63FF",
    fontWeight: "600",
    marginBottom: 4,
  },
  paceDisplay: {
    padding: 8,
    backgroundColor: "#EDEAFE",
    borderRadius: 8,
  },
  paceText: {
    fontSize: 20,
    fontWeight: "700",
    color: "#4A3DBF",
    textAlign: "center",
  },
  paceEmptyText: {
    fontSize: 14,
    color: "#8E8E93",
    textAlign: "center",
  },
  divider: {
    height: 1,
    backgroundColor: "#E8ECF1",
    marginVertical: 20,
  },
  hintContainer: {
    marginTop: 16,
    padding: 14,
    backgroundColor: "#FFF8E1",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#FFD54F",
  },
  hintText: {
    fontSize: 14,
    color: "#F9A825",
    textAlign: "center",
  },
  successContainer: {
    marginTop: 16,
    padding: 14,
    backgroundColor: "#E8F5E9",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#66BB6A",
  },
  successText: {
    fontSize: 14,
    color: "#2E7D32",
    textAlign: "center",
    fontWeight: "600",
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#F5F7FA",
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: "#8E8E93",
  },
  errorText: {
    fontSize: 16,
    color: "#FF3B30",
    textAlign: "center",
    marginBottom: 16,
  },
  retryButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: "#6C63FF",
    borderRadius: 12,
  },
  retryText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  completeText: {
    fontSize: 28,
    fontWeight: "700",
    color: "#34C759",
    marginBottom: 8,
  },
  completeSubtext: {
    fontSize: 16,
    color: "#8E8E93",
    textAlign: "center",
    marginBottom: 24,
  },
  dashboardButton: {
    paddingHorizontal: 32,
    paddingVertical: 16,
    backgroundColor: "#6C63FF",
    borderRadius: 14,
  },
  dashboardButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
});